site_name: "Power-events"
site_description: ""
site_author: "Mathieu LETRONE"
site_dir: "site"
copyright: "Copyright &copy; 2024, Mathieu LETRONE"

repo_name: "mLetrone/power-events"
repo_url: "https://github.com/mLetrone/power-events"

docs_dir: "pages"

theme:
    name: material
    local: en
    features:
        - navigation.sections
        - navigation.top
        - navigation.tabs
        - navigation.footer
        - toc.follow
        - content.code.copy
        - content.code.annotate

nav:
    - Home:
          - Overview: index.md