name: publish-docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: "Publish documentation"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: "Install UV"
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml

      - name: "Install docs dependencies"
        run: uv install --only-group docs

      - name: "Configure Git Credentials"
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: "Build docs with mkdocs"
        run: cd docs && poetry run mkdocs gh-deploy --force