name: publish-docs

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

env:
  UV_PYTHON: "3.9"

jobs:
  new-docs:
    if: "startsWith(github.ref, 'refs/tags/')"
    name: "Publish new version"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: "set up env"
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml

      - name: "Install doc deps"
        run: uv sync --only-group docs

      - name: "Configure Git Credentials"
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: "Get version"
        run: echo "TAG=$(python -c "print('.'.join('${{ github.ref_name }}'.split('.')[:2]))")>>$GITHUB_ENV

      - name: "Publish version $TAG"
        run: uv run mike deploy --push --update-aliases $TAG latest

  update-docs:
    name: "Dev documentation"
    if: "github.ref =='refs/heads/main'"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: "Install UV"
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml

      - name: "Install docs dependencies"
        run: uv sync --only-group docs

      - name: "Configure Git Credentials"
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: "Build docs for dev"
        run: uv run mike deploy --push --update-aliases dev