name: "Release"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "Test tags release"

jobs:
  build:
    name: "Build distribution package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: "Install 'build' library"
        run: pip install -U build

      - name: build
        run: python -m build

      - name: "Upload distribution artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish-pypi:
    name: "Publish to PyPi"
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    environment:
      name: testpypi

    steps:
      - name: "Download distribution artifacts"
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

